-- Phase 4 Royal Glass Validator foundation. IDs are generated by the application,
-- avoiding extension or provider-specific UUID defaults in the Neon schema.

CREATE TABLE competitor_entities (
    id uuid PRIMARY KEY,
    legal_name text NOT NULL,
    display_name text NOT NULL,
    normalized_name text NOT NULL,
    primary_domain text,
    verified_phone text,
    country_code char(2) NOT NULL DEFAULT 'NZ',
    market_priority text NOT NULL DEFAULT 'standard'
        CHECK (market_priority IN ('auckland_high', 'standard')),
    identity_facts jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX competitor_entities_primary_domain_unique
    ON competitor_entities (lower(primary_domain))
    WHERE primary_domain IS NOT NULL;

CREATE TABLE validation_runs (
    id uuid PRIMARY KEY,
    input_workbook_name text NOT NULL,
    input_workbook_sha256 char(64) NOT NULL,
    input_provenance jsonb NOT NULL,
    rule_version text NOT NULL,
    started_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    outcome text NOT NULL DEFAULT 'running'
        CHECK (outcome IN ('running', 'completed', 'failed')),
    summary jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK ((outcome = 'running' AND completed_at IS NULL) OR (outcome <> 'running' AND completed_at IS NOT NULL))
);

CREATE TABLE source_records (
    id uuid PRIMARY KEY,
    validation_run_id uuid NOT NULL REFERENCES validation_runs(id),
    source_system text NOT NULL,
    source_locator text NOT NULL,
    input_row_number integer NOT NULL CHECK (input_row_number > 0),
    original_values jsonb NOT NULL,
    original_value_hash char(64) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id, validation_run_id),
    UNIQUE (validation_run_id, source_locator, input_row_number)
);

CREATE TABLE entity_links (
    id uuid PRIMARY KEY,
    competitor_entity_id uuid NOT NULL REFERENCES competitor_entities(id),
    source_record_id uuid NOT NULL REFERENCES source_records(id),
    link_method text NOT NULL CHECK (link_method IN ('normalized_domain', 'verified_phone_and_name', 'reviewer_resolved')),
    certainty text NOT NULL CHECK (certainty IN ('high', 'reviewer_confirmed')),
    linked_by text NOT NULL CHECK (linked_by IN ('automation', 'reviewer')),
    rationale text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (source_record_id),
    UNIQUE (competitor_entity_id, source_record_id),
    CHECK ((linked_by = 'automation' AND certainty = 'high') OR linked_by = 'reviewer')
);

CREATE TABLE page_evidence (
    id uuid PRIMARY KEY,
    source_record_id uuid NOT NULL,
    competitor_entity_id uuid REFERENCES competitor_entities(id),
    validation_run_id uuid NOT NULL REFERENCES validation_runs(id),
    url text NOT NULL,
    page_title text,
    evidence_snippet text NOT NULL CHECK (char_length(evidence_snippet) BETWEEN 1 AND 1200),
    fetched_at timestamptz NOT NULL,
    content_sha256 char(64) NOT NULL,
    service_facts jsonb NOT NULL DEFAULT '{}'::jsonb,
    region_facts jsonb NOT NULL DEFAULT '{}'::jsonb,
    source_type text NOT NULL CHECK (source_type IN ('official_site', 'business_listing')),
    created_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (source_record_id, validation_run_id) REFERENCES source_records(id, validation_run_id),
    UNIQUE (validation_run_id, url, content_sha256)
);

CREATE TABLE raw_page_snapshots (
    id uuid PRIMARY KEY,
    page_evidence_id uuid NOT NULL UNIQUE REFERENCES page_evidence(id) ON DELETE CASCADE,
    snapshot_body text NOT NULL,
    captured_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL DEFAULT (now() + interval '90 days'),
    CHECK (expires_at >= captured_at)
);

CREATE TABLE fetch_failures (
    id uuid PRIMARY KEY,
    source_record_id uuid NOT NULL,
    competitor_entity_id uuid REFERENCES competitor_entities(id),
    validation_run_id uuid NOT NULL REFERENCES validation_runs(id),
    attempted_url text NOT NULL,
    failure_type text NOT NULL CHECK (failure_type IN ('timeout', 'rate_limited', 'server_error', 'http_error', 'blocked', 'robots_restricted', 'javascript_only', 'missing_site', 'network_error')),
    attempt_number smallint NOT NULL CHECK (attempt_number IN (1, 2)),
    response_status integer,
    detail text,
    occurred_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (source_record_id, validation_run_id) REFERENCES source_records(id, validation_run_id)
);

CREATE TABLE classification_decisions (
    id uuid PRIMARY KEY,
    source_record_id uuid NOT NULL,
    competitor_entity_id uuid REFERENCES competitor_entities(id),
    validation_run_id uuid NOT NULL REFERENCES validation_runs(id),
    proposed_classification text CHECK (proposed_classification IN ('direct', 'adjacent', 'supplier_ecosystem', 'irrelevant')),
    proposed_outcome text NOT NULL CHECK (proposed_outcome IN ('direct', 'adjacent', 'supplier_ecosystem', 'irrelevant', 'review_required')),
    confidence_band text NOT NULL CHECK (confidence_band IN ('high', 'medium', 'low')),
    rationale text NOT NULL,
    tags text[] NOT NULL DEFAULT '{}',
    rule_version text NOT NULL,
    approval_status text NOT NULL DEFAULT 'proposed'
        CHECK (approval_status IN ('proposed', 'auto_approved', 'review_approved')),
    requires_human_review boolean NOT NULL,
    auto_approved boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id, competitor_entity_id),
    FOREIGN KEY (source_record_id, validation_run_id) REFERENCES source_records(id, validation_run_id),
    CHECK (NOT auto_approved OR (
        confidence_band = 'high'
        AND proposed_classification IN ('direct', 'adjacent', 'supplier_ecosystem')
        AND proposed_outcome = proposed_classification
        AND requires_human_review = false
        AND approval_status = 'auto_approved'
    )),
    CHECK (auto_approved OR approval_status <> 'auto_approved'),
    CHECK (proposed_classification <> 'irrelevant' OR proposed_outcome = 'review_required'),
    CHECK (confidence_band = 'high' OR proposed_outcome = 'review_required'),
    CHECK (requires_human_review = (proposed_outcome = 'review_required')),
    CHECK (
        proposed_outcome = 'review_required'
        OR proposed_outcome = proposed_classification
    )
);

CREATE TABLE human_overrides (
    id uuid PRIMARY KEY,
    competitor_entity_id uuid NOT NULL REFERENCES competitor_entities(id),
    classification_decision_id uuid NOT NULL,
    classification text NOT NULL CHECK (classification IN ('direct', 'adjacent', 'supplier_ecosystem', 'irrelevant')),
    rationale text NOT NULL CHECK (char_length(btrim(rationale)) > 0),
    reviewer_identity text NOT NULL CHECK (char_length(btrim(reviewer_identity)) > 0),
    supersedes_override_id uuid UNIQUE REFERENCES human_overrides(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (classification_decision_id, competitor_entity_id)
        REFERENCES classification_decisions(id, competitor_entity_id)
);

CREATE INDEX source_records_validation_run_id_idx ON source_records (validation_run_id);
CREATE INDEX entity_links_competitor_entity_id_idx ON entity_links (competitor_entity_id);
CREATE INDEX page_evidence_competitor_entity_id_idx ON page_evidence (competitor_entity_id);
CREATE INDEX page_evidence_source_record_id_idx ON page_evidence (source_record_id);
CREATE INDEX page_evidence_validation_run_id_idx ON page_evidence (validation_run_id);
CREATE INDEX raw_page_snapshots_expires_at_idx ON raw_page_snapshots (expires_at);
CREATE INDEX fetch_failures_competitor_entity_id_idx ON fetch_failures (competitor_entity_id);
CREATE INDEX fetch_failures_source_record_id_idx ON fetch_failures (source_record_id);
CREATE INDEX classification_decisions_competitor_entity_id_idx ON classification_decisions (competitor_entity_id);
CREATE INDEX classification_decisions_source_record_id_idx ON classification_decisions (source_record_id);
CREATE INDEX classification_decisions_validation_run_id_idx ON classification_decisions (validation_run_id);
CREATE INDEX human_overrides_competitor_entity_id_idx ON human_overrides (competitor_entity_id);

CREATE FUNCTION validator_require_new_run_to_start_running()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.outcome <> 'running' OR NEW.completed_at IS NOT NULL THEN
        RAISE EXCEPTION 'a validation run must start in the running state';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER validation_runs_start_running
BEFORE INSERT ON validation_runs
FOR EACH ROW EXECUTE FUNCTION validator_require_new_run_to_start_running();

CREATE FUNCTION validator_require_open_run_for_source_record()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM validation_runs WHERE id = NEW.validation_run_id AND outcome = 'running'
    ) THEN
        RAISE EXCEPTION 'source records may only be added to a running validation run';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER source_records_require_running_run
BEFORE INSERT ON source_records
FOR EACH ROW EXECUTE FUNCTION validator_require_open_run_for_source_record();

CREATE FUNCTION validator_require_open_run_for_audit_insert()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM validation_runs WHERE id = NEW.validation_run_id AND outcome = 'running'
    ) THEN
        RAISE EXCEPTION 'audit records may only be added to a running validation run';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER page_evidence_require_running_run
BEFORE INSERT ON page_evidence
FOR EACH ROW EXECUTE FUNCTION validator_require_open_run_for_audit_insert();

CREATE TRIGGER fetch_failures_require_running_run
BEFORE INSERT ON fetch_failures
FOR EACH ROW EXECUTE FUNCTION validator_require_open_run_for_audit_insert();

CREATE TRIGGER classification_decisions_require_running_run
BEFORE INSERT ON classification_decisions
FOR EACH ROW EXECUTE FUNCTION validator_require_open_run_for_audit_insert();

CREATE FUNCTION validator_reject_source_record_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'source_records are immutable; import a new record instead';
END;
$$;

CREATE TRIGGER source_records_are_immutable
BEFORE UPDATE OR DELETE ON source_records
FOR EACH ROW EXECUTE FUNCTION validator_reject_source_record_mutation();

CREATE FUNCTION validator_reject_evidence_or_decision_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION '% records are append-only audit history', TG_TABLE_NAME;
END;
$$;

CREATE TRIGGER page_evidence_is_append_only
BEFORE UPDATE OR DELETE ON page_evidence
FOR EACH ROW EXECUTE FUNCTION validator_reject_evidence_or_decision_mutation();

CREATE TRIGGER fetch_failures_are_append_only
BEFORE UPDATE OR DELETE ON fetch_failures
FOR EACH ROW EXECUTE FUNCTION validator_reject_evidence_or_decision_mutation();

CREATE TRIGGER classification_decisions_are_append_only
BEFORE UPDATE OR DELETE ON classification_decisions
FOR EACH ROW EXECUTE FUNCTION validator_reject_evidence_or_decision_mutation();

CREATE FUNCTION validator_reject_human_override_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'human_overrides are immutable; create an explicit superseding override instead';
END;
$$;

CREATE TRIGGER human_overrides_are_immutable
BEFORE UPDATE OR DELETE ON human_overrides
FOR EACH ROW EXECUTE FUNCTION validator_reject_human_override_mutation();

CREATE FUNCTION validator_require_explicit_override_supersession()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    active_override_id uuid;
BEGIN
    PERFORM pg_advisory_xact_lock(hashtext(NEW.competitor_entity_id::text));
    SELECT prior.id
      INTO active_override_id
      FROM human_overrides AS prior
     WHERE prior.competitor_entity_id = NEW.competitor_entity_id
       AND NOT EXISTS (
           SELECT 1
             FROM human_overrides AS successor
            WHERE successor.supersedes_override_id = prior.id
       )
     LIMIT 1;

    IF active_override_id IS NULL AND NEW.supersedes_override_id IS NOT NULL THEN
        RAISE EXCEPTION 'cannot supersede a missing active human override';
    END IF;
    IF active_override_id IS NOT NULL AND NEW.supersedes_override_id IS DISTINCT FROM active_override_id THEN
        RAISE EXCEPTION 'an active human override may only be replaced explicitly';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER human_overrides_require_explicit_supersession
BEFORE INSERT ON human_overrides
FOR EACH ROW EXECUTE FUNCTION validator_require_explicit_override_supersession();

CREATE FUNCTION validator_enforce_validation_run_lifecycle()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.outcome <> 'running' AND NEW IS DISTINCT FROM OLD THEN
        RAISE EXCEPTION 'terminal validation run cannot transition or be modified';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER validation_runs_enforce_lifecycle
BEFORE UPDATE ON validation_runs
FOR EACH ROW EXECUTE FUNCTION validator_enforce_validation_run_lifecycle();

CREATE FUNCTION validator_require_completed_run_audit_history()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.outcome = 'running' AND NEW.outcome = 'completed' THEN
        IF EXISTS (
            SELECT 1
              FROM source_records AS source
             WHERE source.validation_run_id = NEW.id
               AND NOT EXISTS (
                   SELECT 1
                     FROM classification_decisions AS decision
                    WHERE decision.source_record_id = source.id
                      AND decision.validation_run_id = NEW.id
               )
        ) THEN
            RAISE EXCEPTION 'a completed validation run requires a decision for every source record';
        END IF;
        IF EXISTS (
            SELECT 1
              FROM classification_decisions AS decision
             WHERE decision.validation_run_id = NEW.id
               AND NOT EXISTS (
                   SELECT 1
                     FROM page_evidence AS evidence
                    WHERE evidence.source_record_id = decision.source_record_id
                      AND evidence.validation_run_id = NEW.id
               )
               AND NOT EXISTS (
                   SELECT 1
                     FROM fetch_failures AS failure
                    WHERE failure.source_record_id = decision.source_record_id
                      AND failure.validation_run_id = NEW.id
               )
        ) THEN
            RAISE EXCEPTION 'a completed validation decision requires evidence or a captured fetch failure';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER validation_runs_require_audit_history_when_completed
BEFORE UPDATE OF outcome ON validation_runs
FOR EACH ROW EXECUTE FUNCTION validator_require_completed_run_audit_history();

CREATE FUNCTION prune_expired_raw_page_snapshots()
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    deleted_count integer;
BEGIN
    DELETE FROM raw_page_snapshots WHERE expires_at <= now();
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END;
$$;
